# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET release

on:
  workflow_dispatch

env:
  NuGetDirectory: ${{ github.workspace}}/nuget

jobs:
  build:
    name: release
    
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release 
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release 
      
    - name: GetVersion
      id: package_version
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
        file: PowerCollections/PowerCollections.csproj
      
    - name: Pack
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
     
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sofiasketch.PowerCollections.{{ steps.package_version.outputs.version }}.nupkg
        path: ${{ env.NuGetDirectory }}/*.nupkg
      
    - name: Push
      run: dotnet nuget push "**/sofiasketch.PowerCollections.{{ steps.package_version.outputs.version }}.nupkg" --skip-duplicate --api-key ${{ secrets.TOKEN  }} --source "https://nuget.pkg.github.com/sofiasketch/index.json"
      
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "sofiasketch.PowerCollections.{{ steps.package_version.outputs.version }}.nupkg"
        tag: "v${{ steps.package_version.outputs.version }}"

