# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET release

on:
  workflow_dispatch

env:
  NuGetDirectory: ${{ github.workspace}}/nuget

jobs:
  build:
    name: release
    
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release 
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release 
      
    - name: GetVersion
      id: package_version
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
        file: PowerCollections/PowerCollections.csproj
      
    - name: Pack
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
      
    - name: Push
      run: dotnet nuget push "${{ env.NuGetDirectory }}/sofiasketch.PowerCollections.${{ steps.package_version.outputs.version }}.nupkg" --skip-duplicate --api-key ${{ secrets.TOKEN  }} --source "https://nuget.pkg.github.com/sofiasketch/index.json"
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ steps.package_version.outputs.version }}"
        files: ${{ env.NuGetDirectory }}/*.nupkg

